#ifndef GRAPHICS_GRAPHICS_EVENTS_H
#define GRAPHICS_GRAPHICS_EVENTS_H

#define FULL_REDRAW BIT0
#define PROGRESS_ADVANCE BIT1
#define NEW_SONG BIT2
#define NEW_IMAGE BIT3
#define STATUS_CHANGED BIT4
#define VOLUME_CHANGED BIT5
#define SECOND_OVER BIT6

#endif